# Form implementation generated from reading ui file 'forms/file.ui'
#
# Created by: PyQt6 UI code generator 6.1.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddFileMenu(object):
    def setupUi(self, AddFileMenu):
        AddFileMenu.setObjectName("AddFileMenu")
        AddFileMenu.resize(453, 218)
        self.gridLayout = QtWidgets.QGridLayout(AddFileMenu)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.chooseFileButton = QtWidgets.QPushButton(AddFileMenu)
        self.chooseFileButton.setObjectName("chooseFileButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.chooseFileButton)
        self.filePath = QtWidgets.QLineEdit(AddFileMenu)
        self.filePath.setObjectName("filePath")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.filePath)
        self.label_2 = QtWidgets.QLabel(AddFileMenu)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.destinationPath = QtWidgets.QLineEdit(AddFileMenu)
        self.destinationPath.setObjectName("destinationPath")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.destinationPath)
        self.label_4 = QtWidgets.QLabel(AddFileMenu)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.description = QtWidgets.QLineEdit(AddFileMenu)
        self.description.setObjectName("description")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.description)
        self.verticalLayout.addLayout(self.formLayout)
        self.useHome = QtWidgets.QCheckBox(AddFileMenu)
        self.useHome.setChecked(True)
        self.useHome.setObjectName("useHome")
        self.verticalLayout.addWidget(self.useHome)
        self.isRequired = QtWidgets.QCheckBox(AddFileMenu)
        self.isRequired.setChecked(True)
        self.isRequired.setObjectName("isRequired")
        self.verticalLayout.addWidget(self.isRequired)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cancelButton = QtWidgets.QPushButton(AddFileMenu)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.addFile = QtWidgets.QPushButton(AddFileMenu)
        self.addFile.setObjectName("addFile")
        self.horizontalLayout.addWidget(self.addFile)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(AddFileMenu)
        QtCore.QMetaObject.connectSlotsByName(AddFileMenu)

    def retranslateUi(self, AddFileMenu):
        _translate = QtCore.QCoreApplication.translate
        AddFileMenu.setWindowTitle(_translate("AddFileMenu", "Add file"))
        self.chooseFileButton.setText(_translate("AddFileMenu", "Choose file"))
        self.label_2.setText(_translate("AddFileMenu", "Place to"))
        self.label_4.setText(_translate("AddFileMenu", "Description"))
        self.useHome.setText(_translate("AddFileMenu", "Use home folder as root"))
        self.isRequired.setText(_translate("AddFileMenu", "Required"))
        self.cancelButton.setText(_translate("AddFileMenu", "Cancel"))
        self.addFile.setText(_translate("AddFileMenu", "Add"))
