name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
          
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.7.11'
          
      - name: Get the version
        id: get_version
        shell: bash
        run: |
          VERSION=${GITHUB_REF/refs\/tags\//}
          echo ::set-output name=VERSION::$VERSION
        
      - name: Build package
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
          pyinstaller main.py --onefile --name bi-creator
          mv ${{ github.workspace }}/dist/bi-creator ${{ github.workspace }}/dist/bi-creator-ubuntu-20-04-focal
        
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/dist/*
          name: Bi-Creator ${{steps.get_version.outputs.VERSION}}
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
